"""add extra fields to recipe

Revision ID: 28765bb239fa
Revises: 176a2ebd2194
Create Date: 2026-04-13 19:06:01.018365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28765bb239fa'
down_revision = '176a2ebd2194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allergy_warnings', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('allergy_warnings')
        batch_op.drop_column('servings')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
